name: intelli_farm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.9      # ✅ Add this
  image_picker: ^1.1.2
  dio: 4.0.6
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  http: 0.13.6
  translator: ^0.1.7
  provider: ^6.0.5
  uuid: ^4.5.1
  webview_flutter: ^4.7.0
  ffi: ^2.1.4
  flutter_spinkit: ^5.2.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0               # ✅ Add this
  permission_handler: ^11.3.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3       # ✅ Add this
  open_weather_widget: ^0.0.3
  weather: 3.0.0
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/farmerchatbot-xtii-45019ce0b910.json
    - assets/images/sc1.jpg
    - assets/images/sc2.jpg
    - assets/images/sc3.jpg
    - assets/images/sc4.jpg
#    - assets/images/scheme1.jpeg
#    - assets/images/scheme2.jpeg
#   - assets/images/scheme3.jpeg
#   - assets/images/scheme4.jpeg
#   - assets/images/scheme5.jpeg
    - assets/logo.jpg
    - assets/fertilizers1.jpg
    - assets/fertilizers2.jpg
    - assets/fertilizers3.jpg
    - assets/products1.jpg
    - assets/products2.jpg
    - assets/products3.jpg
    - assets/crops/Bajra.png
    - assets/crops/Banana.png
    - assets/crops/Barley.png
    - assets/crops/Beans.png
    - assets/crops/Beetroot.png
    - assets/crops/Brinjal.png
    - assets/crops/Cabbage.png
    - assets/crops/Carrot.png
    - assets/crops/Cauliflower.png
    - assets/crops/Chilli.png
    - assets/crops/Coconut.png
    - assets/crops/Cotton.png
    - assets/crops/Garlic.png
    - assets/crops/Ginger.png
    - assets/crops/Groundnut.png
    - assets/crops/Guava.png
    - assets/crops/Lettuce.png
    - assets/crops/Maize.png
    - assets/crops/Mango.png
    - assets/crops/Mustard.png
    - assets/crops/Onion.png
    - assets/crops/Paddy.png
    - assets/crops/Papaya.png
    - assets/crops/Peas.png
    - assets/crops/Pomegranate.png
    - assets/crops/Potato.png
    - assets/crops/Radish.png
    - assets/crops/Soybean.png
    - assets/crops/Spinach.png
    - assets/crops/Sugarcane.png
    - assets/crops/Sunflower.png
    - assets/crops/SweetPotato.png
    - assets/crops/Tomato.png
    - assets/crops/Turmeric.png
    - assets/crops/Wheat.png

